% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={463\_HW\_3},
  pdfauthor={Benjamin Wang},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{463\_HW\_3}
\author{Benjamin Wang}
\date{2023-03-09}

\begin{document}
\maketitle

\hypertarget{assignment-2}{%
\subsection{Assignment 2}\label{assignment-2}}

An amateur brewer wishes to better understand how the temperature that
the beer ferments at (in degrees Fahrenheit) affects the alcohol content
of the beer upon completion of brewing. Fortunately, the brewer has kept
copious notes on his many brewing endeavors and has records for each
batch on what temperature the beer fermented at and what the final
alcohol content was.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modeling }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{"./modeling\_data.txt"}\NormalTok{,}\AttributeTok{sep=}\StringTok{"}\SpecialCharTok{\textbackslash{}t}\StringTok{"}\NormalTok{,}\AttributeTok{header=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Using the modeling dataset, visually display the data in an
  appropriate graph and comment on anything that may be of note. In
  particular, are the assumptions needed for fitting the simple linear
  model met?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modeling\_lm }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Alcohol\_Percentage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Temperature, }\AttributeTok{data=}\NormalTok{modeling)}
\FunctionTok{plot}\NormalTok{(}
\NormalTok{  Alcohol\_Percentage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Temperature, }\AttributeTok{data=}\NormalTok{modeling,}
  \AttributeTok{main=}\StringTok{"Alcohol Percentage vs Temperature"}\NormalTok{,}
  \AttributeTok{xlab=}\StringTok{"Temperature (degrees F)"}\NormalTok{,}
  \AttributeTok{ylab=}\StringTok{"Alcohol Percentage"}
\NormalTok{)}
\FunctionTok{abline}\NormalTok{(modeling\_lm,}\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{463_HW_3_files/figure-latex/unnamed-chunk-2-1.pdf}

In this plot, we can see that there is an extraneous recording (outlier)
with a negative alcohol percentage. It may be necessary to remove this
outlier before fitting a simple linear model. However, at a glance it
seems to be appropriate to apply a simple linear model to the modeling
data.

For the plot above, the outlier is not visualized because it is
important to see the observations with more granularity.

Addressing regression assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Linearity - observations are mostly on the line and therefore
  appropriate.
\item
  Homoscedasticity - this assumption is violated.
\item
  Normality of errors - Errors are mostly normal but are positively
  skewed, suggesting that there may be some non-normality in the
  distribution. However, it is appropriate.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(}\FunctionTok{resid}\NormalTok{(modeling\_lm),}\AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{qqline}\NormalTok{(}\FunctionTok{resid}\NormalTok{(modeling\_lm),}\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{463_HW_3_files/figure-latex/unnamed-chunk-3-1.pdf}

For the plot above, there is an outlier that is not visualized because
it is important to see the observations with more granularity.

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Initially, the brewer would just like to get a rough estimate of what
  the alcohol content would be if he ferments the batch at a given
  temperature. Are enough of the regression assumptions satisfied so
  that simple linear regression can be used towards the prior-mentioned
  goal? If not, what deviations do you need to address and how do you
  address them?
\end{enumerate}

Enough of the regression assumptions are satisfied, so we can use the
simple linear regression model. However, we must address the outlier,
which we can handle by simply removing the data point from our
observation.

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  After addressing any necessary issues in part 2, fit the simple linear
  model to the data. Provide the parameter estimates and the R\^{}2
  value. Overlay the estimated regression line on the plot created in
  part 1.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modeling\_no\_outliers }\OtherTok{=}\NormalTok{ modeling[modeling}\SpecialCharTok{$}\NormalTok{Alcohol\_Percentage }\SpecialCharTok{\textgreater{}=} \DecValTok{0}\NormalTok{,]}
\FunctionTok{plot}\NormalTok{(}
\NormalTok{  Alcohol\_Percentage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Temperature, }\AttributeTok{data=}\NormalTok{modeling\_no\_outliers,}
  \AttributeTok{main=}\StringTok{"Alcohol Percentage vs Temperature"}\NormalTok{,}
  \AttributeTok{xlab=}\StringTok{"Temperature (degrees F)"}\NormalTok{,}
  \AttributeTok{ylab=}\StringTok{"Alcohol Percentage"}\NormalTok{,}
  \AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{8}\NormalTok{)}
\NormalTok{)}

\NormalTok{modeling\_no\_outliers\_lm }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Alcohol\_Percentage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Temperature, }\AttributeTok{data=}\NormalTok{modeling\_no\_outliers)}
\FunctionTok{abline}\NormalTok{(modeling\_no\_outliers\_lm, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{463_HW_3_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(modeling\_no\_outliers\_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Alcohol_Percentage ~ Temperature, data = modeling_no_outliers)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.12419 -0.21920 -0.05328  0.19142  1.42246 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 26.173742   0.613251   42.68   <2e-16 ***
## Temperature -0.357968   0.009907  -36.13   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.38 on 197 degrees of freedom
## Multiple R-squared:  0.8689, Adjusted R-squared:  0.8682 
## F-statistic:  1306 on 1 and 197 DF,  p-value: < 2.2e-16
\end{verbatim}

The R\^{}2 value is 0.8689. The parameter estimates are:

\begin{itemize}
\item
  Intercept = 26.173742
\item
  Temperature = -0.357968
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Now turn attention to the validation dataset. In order to assess how
  well the model works, calculate the predicted values using the batch
  temperatures from the validation dataset and the model from part 3.
  Plot these predicted values versus the actual values (the actual
  alcohol content) from the validation dataset in a scatter plot.
  Additionally, calculate the sample correlation between the predicted
  values and the actual values.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{validation }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{"./validation\_data.txt"}\NormalTok{,}\AttributeTok{sep=}\StringTok{"}\SpecialCharTok{\textbackslash{}t}\StringTok{"}\NormalTok{,}\AttributeTok{header=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{predicted }\OtherTok{=} \FunctionTok{predict}\NormalTok{(modeling\_no\_outliers\_lm, }\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Temperature=}\NormalTok{validation[,}\DecValTok{1}\NormalTok{]))}
\NormalTok{comparison }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Predicted=}\NormalTok{predicted, }\AttributeTok{Observed=}\NormalTok{validation[,}\DecValTok{2}\NormalTok{])}
\NormalTok{comparison\_lm }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Predicted }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Observed, }\AttributeTok{data=}\NormalTok{comparison)}
\FunctionTok{plot}\NormalTok{(Predicted }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Observed, }\AttributeTok{data=}\NormalTok{comparison,}\AttributeTok{pch=}\DecValTok{20}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(comparison\_lm,}\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{463_HW_3_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(comparison}\SpecialCharTok{$}\NormalTok{Observed, comparison}\SpecialCharTok{$}\NormalTok{Predicted)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9170591
\end{verbatim}

The sample correlation between predicted and actual is 0.9170591.

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  As is evident from part 1, for a given fermentation temperature, there
  is a tremendous amount of variability in the alcohol content of the
  batch. Consequently, for any given temperature, the brewer would like
  to get bands that encompass what the final alcohol content of a batch
  would be with probability 95\%. Were the steps taken in part 2 enough
  to still warrant the use of simple linear regression for this goal, or
  are there still model deviations that need to be addressed? If so,
  what are the remaining deviations and how do you address them?
\end{enumerate}

The steps taken in part 2 were not enough to warrant the use of simple
linear regression for this goal, because of the heteroscedasticity. The
heteroscedasticity in the model must be addressed, which we handle with
weighted least squares regression.

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
  After addressing any additional issues in part 5, obtain a new model
  for the data. Describe how you arrived at this model. For a given
  temperature, x, write out the formula for the predicted alcohol
  content specified for your model. Overlay the estimated regression
  curve on the plot created in part 1.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modeling\_no\_outliers\_residuals }\OtherTok{=} \FunctionTok{resid}\NormalTok{(modeling\_no\_outliers\_lm)}
\NormalTok{modeling\_weights }\OtherTok{=} \FunctionTok{fitted}\NormalTok{( }\FunctionTok{lm}\NormalTok{(}\FunctionTok{abs}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(modeling\_no\_outliers\_lm))}\SpecialCharTok{\textasciitilde{}}\FunctionTok{fitted}\NormalTok{(modeling\_no\_outliers\_lm)) )}\SpecialCharTok{\^{}}\DecValTok{2}

\NormalTok{wls\_transformed }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Alcohol\_Percentage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Temperature, }\AttributeTok{data=}\NormalTok{modeling\_no\_outliers, }\AttributeTok{weights=}\NormalTok{modeling\_weights)}

\FunctionTok{plot}\NormalTok{(}
\NormalTok{  Alcohol\_Percentage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Temperature, }\AttributeTok{data=}\NormalTok{modeling,}
  \AttributeTok{main=}\StringTok{"Alcohol Percentage vs Temperature"}\NormalTok{,}
  \AttributeTok{xlab=}\StringTok{"Temperature (degrees F)"}\NormalTok{,}
  \AttributeTok{ylab=}\StringTok{"Alcohol Percentage"}\NormalTok{,}
  \AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{8}\NormalTok{)}
\NormalTok{)}
\FunctionTok{abline}\NormalTok{(modeling\_lm,}\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(wls\_transformed,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{463_HW_3_files/figure-latex/unnamed-chunk-6-1.pdf}

I arrived at this model using the weighted least squares regression
model. I determined that a WLS regression model would be appropriate
because it assigns lower weights to points with higher variance and thus
could mitigate the heteroscedasticity of the model. The weighted least
squares regression model is displayed in blue.

For a given temperature x, we have the function f(x) which is given as:

f(x) = -0.356431*x + 26.079850

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
  Repeat part 4, this time using the model you obtained in part 6.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predicted\_wls }\OtherTok{=} \FunctionTok{predict}\NormalTok{(wls\_transformed, }\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Temperature=}\NormalTok{validation[,}\DecValTok{1}\NormalTok{]))}
\NormalTok{comparison\_wls }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Predicted=}\NormalTok{predicted\_wls, }\AttributeTok{Observed=}\NormalTok{validation[,}\DecValTok{2}\NormalTok{])}
\NormalTok{comparison\_wls\_lm }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Predicted }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Observed, }\AttributeTok{data=}\NormalTok{comparison\_wls)}
\FunctionTok{plot}\NormalTok{(Predicted }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Observed, }\AttributeTok{data=}\NormalTok{comparison\_wls,}\AttributeTok{pch=}\DecValTok{20}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(comparison\_wls\_lm,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{463_HW_3_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(comparison\_wls}\SpecialCharTok{$}\NormalTok{Observed, comparison\_wls}\SpecialCharTok{$}\NormalTok{Predicted)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9170591
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  As mentioned in part 5, for any given fermentation temperature the
  brewer would like to obtain bands that encompass what the final
  alcohol content of a batch would be with probability 95\%. Write out a
  formula for the upper and lower endpoints for these bands as a
  function of the explanatory variable (possibly transformed). Overlay
  these bands on the plot created in part 1.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}
\NormalTok{  Alcohol\_Percentage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Temperature, }\AttributeTok{data=}\NormalTok{modeling\_no\_outliers,}
  \AttributeTok{main=}\StringTok{"Alcohol Percentage vs Temperature"}\NormalTok{,}
  \AttributeTok{xlab=}\StringTok{"Temperature (degrees F)"}\NormalTok{,}
  \AttributeTok{ylab=}\StringTok{"Alcohol Percentage"}\NormalTok{,}
  \AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{8}\NormalTok{)}
\NormalTok{)}

\NormalTok{modeling\_no\_outliers\_lm }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Alcohol\_Percentage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Temperature, }\AttributeTok{data=}\NormalTok{modeling\_no\_outliers)}
\FunctionTok{abline}\NormalTok{(wls\_transformed,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}

\NormalTok{conf\_int }\OtherTok{=} \FunctionTok{predict}\NormalTok{(modeling\_no\_outliers\_lm, }\AttributeTok{interval=}\StringTok{"prediction"}\NormalTok{, }\AttributeTok{level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predict.lm(modeling_no_outliers_lm, interval = "prediction", : predictions on current data refer to _future_ responses
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{conf\_int }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(modeling\_no\_outliers}\SpecialCharTok{$}\NormalTok{Temperature, conf\_int)}
\NormalTok{conf\_int }\OtherTok{=}\NormalTok{ conf\_int[}\FunctionTok{order}\NormalTok{(conf\_int[,}\DecValTok{1}\NormalTok{]),]}
\FunctionTok{points}\NormalTok{(conf\_int[,}\DecValTok{1}\NormalTok{], conf\_int[,}\DecValTok{3}\NormalTok{], }\AttributeTok{type=}\StringTok{"l"}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\DecValTok{3}\NormalTok{)}
\FunctionTok{points}\NormalTok{(conf\_int[,}\DecValTok{1}\NormalTok{], conf\_int[,}\DecValTok{4}\NormalTok{], }\AttributeTok{type=}\StringTok{"l"}\NormalTok{, }\AttributeTok{lty=}\DecValTok{2}\NormalTok{, }\AttributeTok{col =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{463_HW_3_files/figure-latex/unnamed-chunk-8-1.pdf}

\end{document}
